class AlreadyPausedException(Exception): pass
class AlreadyResumedException(Exception): pass
class AlreadyEndedException(Exception): pass